name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_DIR: 'certificate_download_site-ui'
  AZURE_WEBAPP_PACKAGE_PATH: 'build'

concurrency:
  group: deploy-azure-webapp
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package_path: ${{ steps.prepare.outputs.package_path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect app directory
        id: detect-dir
        shell: bash
        run: |
          ROOT="${GITHUB_WORKSPACE:-.}"
          if [ -f "$ROOT/certificate_download_site-ui/package.json" ] && [ -f "$ROOT/certificate_download_site-ui/vite.config.js" ]; then
            echo "app_dir=certificate_download_site-ui" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ] && [ -f "vite.config.js" ]; then
            echo "app_dir=." >> $GITHUB_OUTPUT
          else
            echo "app_dir=." >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        shell: bash
        run: |
          APP_DIR="${{ steps.detect-dir.outputs.app_dir }}"
          if [ "$APP_DIR" = "." ]; then
            npm ci
          else
            npm --prefix "$APP_DIR" ci
          fi

      - name: Create .env.production from secrets
        shell: bash
        run: |
          set -e
          APP_DIR="${{ steps.detect-dir.outputs.app_dir }}"
          mkdir -p "$APP_DIR"
          cat > "$APP_DIR/.env.production" <<EOF
          VITE_MSAL_TENANT_ID=${{ secrets.VITE_MSAL_TENANT_ID }}
          VITE_MSAL_CLIENT_ID=${{ secrets.VITE_MSAL_CLIENT_ID }}
          VITE_MSAL_AUTHORITY=${{ secrets.VITE_MSAL_AUTHORITY }}
          VITE_ALLOWED_EMAIL_DOMAIN=${{ secrets.VITE_ALLOWED_EMAIL_DOMAIN }}
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          VITE_REDIRECT_URI=${{ secrets.VITE_REDIRECT_URI }}
          EOF

      - name: Build application
        shell: bash
        env:
          VITE_MSAL_TENANT_ID: ${{ secrets.VITE_MSAL_TENANT_ID }}
          VITE_MSAL_CLIENT_ID: ${{ secrets.VITE_MSAL_CLIENT_ID }}
          VITE_MSAL_AUTHORITY: ${{ secrets.VITE_MSAL_AUTHORITY }}
          VITE_ALLOWED_EMAIL_DOMAIN: ${{ secrets.VITE_ALLOWED_EMAIL_DOMAIN }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          APP_DIR="${{ steps.detect-dir.outputs.app_dir }}"
          if [ "$APP_DIR" = "." ]; then
            npm run build
          else
            npm --prefix "$APP_DIR" run build
          fi

      - name: Prepare build artifact (ensure web.config present)
        id: prepare
        shell: bash
        run: |
          set -e
          APP_DIR="${{ steps.detect-dir.outputs.app_dir }}"
          ROOT="${GITHUB_WORKSPACE:-$(pwd)}"
          # Determine actual build output directory relative to repo root
          if [ -d "$ROOT/build" ]; then
            PACKAGE_REL="build"
          elif [ -d "$ROOT/dist" ]; then
            PACKAGE_REL="dist"
          elif [ -d "$ROOT/$APP_DIR/build" ]; then
            PACKAGE_REL="$APP_DIR/build"
          elif [ -d "$ROOT/$APP_DIR/dist" ]; then
            PACKAGE_REL="$APP_DIR/dist"
          else
            echo "::error::Build output directory not found (checked $ROOT/build, $ROOT/dist, $ROOT/$APP_DIR/build, $ROOT/$APP_DIR/dist)"
            echo "Root listing ($ROOT):" && ls -la "$ROOT" || true
            echo "$APP_DIR listing ($ROOT/$APP_DIR):" && ls -la "$ROOT/$APP_DIR" || true
            exit 1
          fi

          # Propagate the resolved package path to later steps in this job (relative to repo root)
          echo "AZURE_WEBAPP_PACKAGE_PATH=$PACKAGE_REL" >> "$GITHUB_ENV"
          echo "package_path=$PACKAGE_REL" >> "$GITHUB_OUTPUT"

          # Ensure SPA fallback web.config is present
          WEB_SRC="$ROOT/$APP_DIR/public/web.config"
          if [ -f "$WEB_SRC" ]; then
            cp -f "$WEB_SRC" "$ROOT/$PACKAGE_REL/web.config"
          fi

      - name: Generate runtime-config.js (runtime config for SPA)
        shell: bash
        run: |
          set -e
          PACKAGE_PATH='${{ steps.prepare.outputs.package_path }}'
          cat > "$PACKAGE_PATH/runtime-config.js" <<'EOF'
          (function(w){
            w.__RUNTIME_CONFIG__ = {
              MSAL_TENANT_ID: "${{ secrets.VITE_MSAL_TENANT_ID }}",
              MSAL_CLIENT_ID: "${{ secrets.VITE_MSAL_CLIENT_ID }}",
              MSAL_AUTHORITY: "${{ secrets.VITE_MSAL_AUTHORITY }}",
              REDIRECT_URI: "${{ secrets.VITE_REDIRECT_URI }}",
              ALLOWED_EMAIL_DOMAIN: "${{ secrets.VITE_ALLOWED_EMAIL_DOMAIN }}",
              API_BASE_URL: "${{ secrets.VITE_API_BASE_URL }}"
            };
            w.__API_BASE_URL__ = w.__RUNTIME_CONFIG__.API_BASE_URL || w.__API_BASE_URL__;
          })(window);
          EOF

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ steps.prepare.outputs.package_path }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ needs.build.outputs.package_path }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ needs.build.outputs.package_path }}
